### ISSUE TITLE
Inconsistent line endings

### ISSUE THREAD

**Issue by pixelchutes** [FoxyCart/2.0-templates#2]
It seems the files in this repo do not use a consistent file format / line ending. I ran into this by cloning the repo and forking into a custom branch in order to customize the Twig templates, and still be able to easily merge from upstream `master` to leverage future fixes / improvements, etc.

In my case, simply changing one line of code in the Responsive Email Twig file resulted in Git `diff`'ing the entire file ...but this only happened on *some* of the modified files, not all. While this may be unavoidable depending on developer IDE / editor preference, it might still be valuable establishing a consistent file format / line endings that devs can then reliably support, especially to avoid potential future conflicts when merging from upstream.

For example, compare some of the files in **default_templates**, such as: `responsive.email.twig` *[dos, CRLF]* or `responsive.cart.twig` *[unix, LF]*, `responsive.receipt.twig` *[dos, CRLF]* etc.

**Comment by evgenius** [comment]
Good point @pixelchutes .
10 files have Unix-style line endings vs. 9 files with Windows style.
